modLoader = "javafml"
loaderVersion = "[${forge_version},)"
#issueTrackerURL = ""
license = "GPL-3.0"

[[mods]]
modId = "create_unbreakable"
version = "${version}"
displayName = "Create Unbreakable Tools"
authors = "anvian"
description = ""
logoFile = "icon.png"

[[dependencies.create_unbreakable]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.create_unbreakable]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version}"
ordering = "NONE"
side = "BOTH"

[[dependencies.create_unbreakable]]
modId="create"
mandatory=true
versionRange="${create_version}"
ordering="NONE"
side="BOTH"