modLoader = "javafml"
loaderVersion = "[${forge_version},)"

issueTrackerURL = "https://github.com/anviaan/CreateUnbreakableTools/issues"
license = "GPL-3.0"

[[mods]]
modId = "create_unbreakable"
version = "${version}"
displayName = "Create Unbreakable Tools Mod"
credits = ["PinhaColada2222", "awadito2"]
authors = "anvian"
description = "This is an addon mod for Create in Fabric that provides the ability to make your tools unbreakable."
logoFile = "icon.png"
displayURL= "https://github.com/anviaan/CreateUnbreakableTools"

[[dependencies.create_unbreakable]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.create_unbreakable]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version}"
ordering = "NONE"
side = "BOTH"

[[dependencies.create_unbreakable]]
modId="create"
mandatory=true
versionRange="[${create_version},)"
ordering="NONE"
side="BOTH"